apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit-cluster
    app: nameko-miniservice
  name: rabbit-cluster
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit-cluster
        app: nameko-miniservice
    spec:
      containers:
      - image: wcs2releases.azurecr.io/nameko/rabbit-cluster:latest
        name: rabbit-cluster
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
      hostname: rabbit-cluster
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
