version: "2"
services:

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    expose:
      - 5672

  redis:
    image: redis:5-alpine
    expose:
      - 6379

  hello:
    build:
      context: hello
    links:
      - rabbit
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  gateway:
    build:
      context: gateway
    links:
      - rabbit
      - redis
    depends_on:
      - hello
    ports:
        - "8000:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      GATEWAY_HOST: "0.0.0.0"
      GATEWAY_PORT: "8000"
      FLASK_ENV: "testing"
      ENV_FOR_DYNACONF: "testing"
