version: "2"

volumes:
  pgdb:

services:

# Pre-requisities

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  redis:
    image: redis:5-alpine

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - pgdb:/var/lib/postgresql/data

  sentry:
    image: sentry:9
    ports:
      - 9000:9000
    links:
      - redis
      - postgres
    environment:
      SENTRY_SECRET_KEY: "OcR3opOZtaxwptoW3peiwIHi4r9fgBIp"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  sentry-cron:
    image: sentry:9
    links:
      - redis
      - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: "OcR3opOZtaxwptoW3peiwIHi4r9fgBIp"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  sentry-worker:
    image: sentry:9
    links:
      - redis
      - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: "OcR3opOZtaxwptoW3peiwIHi4r9fgBIp"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

# Cloud application

  hello:
    build:
      context: hello
    links:
      - rabbit
      - sentry
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      SENTRY_PUBLIC_KEY: ${SENTRY_PUBLIC_KEY}
      SENTRY_HOST: "sentry"
      SENTRY_PORT: "9000"

  auth:
    build:
      context: auth
    links:
      - rabbit
      - sentry
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      SENTRY_PUBLIC_KEY: ${SENTRY_PUBLIC_KEY}
      SENTRY_HOST: "sentry"
      SENTRY_PORT: "9000"

  gateway:
    build:
      context: gateway
    links:
      - rabbit
      - redis
    depends_on:
      - hello
    ports:
        - 8000:8000
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      GATEWAY_HOST: "0.0.0.0"
      GATEWAY_PORT: "8000"
      FLASK_ENV: "testing"
      ENV_FOR_DYNACONF: "testing"
