[development]
rabbit_uri = "amqp://guest:guest@localhost:5672"
redis_host = "localhost"
redis_port = 6379

[testing]
rabbit_uri = "amqp://guest:guest@rabbit:5672"
redis_host = "redis"
redis_port = 6379