apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: hello
    app: nameko-miniservice
  name: hello
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hello
        app: nameko-miniservice
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbit-cluster
        - name: RABBIT_MGMT_PORT
          value: "15672"
        - name: RABBIT_PASSWORD
          value: guest
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: guest
        - name: SENTRY_HOST
          value: sentry
        - name: SENTRY_PORT
          value: "9000"
        - name: SENTRY_PUBLIC_KEY
          value: e13d1bff0c314af9963e4c1d76e9f7d9
        image: wcs2releases.azurecr.io/nameko/hello:latest
        name: hello
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
