apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pgdb
    app: nameko-miniservice
  name: pgdb
spec:
  capacity:
    storage: 100Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
