apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
    app: nameko-miniservice
  name: postgres
spec:
  ports:
  - name: "5342"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres
  clusterIP: "None"
status: {}
