apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit-master
    app: nameko-miniservice
  name: rabbit-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit-master
        app: nameko-miniservice
    spec:
      containers:
      - env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: ZmKpvN2hDMpb5mYY
        image: wcs2releases.azurecr.io/nameko/rabbit-master:latest
        name: rabbit-master
        resources: {}
      hostname: rabbit-master
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
